spring:
  application:
    name: eureka-feign-front-client
server:
  port: 8189
  servlet:
    context-path: /market

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}